### ISSUE TITLE
Airship map screenshots

### ISSUE THREAD

**Issue by JLpython-py** [JLpython-py/Among-Us-Bot#50]
Screenshots of the Airship map are needed and will be added to **data/Airship/\*\*/**.

<h2>Screenshots Needed</h2>

Screenshots are needed for each of the following categories:

- Actions
- Locations
- Maps*
- Tasks
- Vents

*_The annotated map won't be a screenshot and likely will be added much later_.

For a comprehensive list of every item to screenshot, check the CSV files in the [AmongUsData repository](https://github.com/JLpython-py/AmongUsData)

<h2>Image Guidlines</h2>

When taking screenshots, the following guidelines are recommended for the purpose of consistency:

- Name yourself 'Player' and change your color to red
- It is recommended that all screenshots be taken in the **Freeplay** mode
- Hide the tasks list
- For all categories excluding *tasks*, it is recommended that you change yourself to the Impostor
- Screenshots should be of the entire screen
- It is perfectly okay if the Dummy players are in the picture!

When naming the screenshots, make sure that they are **.png** formatted and are the name of the item (titlecase with spaces), e.g. **The Name Of My Image.png**

For references, check the existing screenshots in **data/MIRAHQ/**, **data/Polus/**, and **data/TheSkeld**.

<h2>Submitting Images</h2>

1. Clone this repository
2. Create a branch called `Airship/username-goes-here`
3. Create a **Pull Request** to merge your branch onto the `Airship` branch

Any help is much appreciated, as it will allow me to work on other issues.

**Comment by JLpython-py** [comment]
If you do not want to create a separate branch for your images, you can create a comment and upload the image(s) from your device.

**Comment by Pietrodjaowjao** [comment]
i have all sprites and room names of airship i can send in discord

**Comment by JLpython-py** [comment]
> i have all sprites and room names of airship i can send in discord

If you are comfortable sharing images of the sprites, you can add them as an image. However, I completely understand if you do not want to. 

As for the room names, if you are able to read the Airship database in this repository, you could try to double-check the names of the rooms which I had found. Otherwise, you could send it here and I will double-check myself. 

As for communicating through Discord, I may set up a Developer Build guild and add an invite link it to the repository.

**Comment by JLpython-py** [comment]
Coverage is being worked on in `update/airship`.
